### ISSUE TITLE
This tool seems interesting, any doc?

### ISSUE THREAD

**Issue by Pierstoval** [obiwankennedy/phpbb-poster-browser#1]
I know this is quite an alpha stage, but posting on phpBB programmatically with this kind of tool is really interesting 😄 

Any doc on how to build this app and try it?
Or at least any pre-built binary that one could use?

**Comment by obiwankennedy** [comment]
It is not really meant to be published or released. As it can be a major weapon to spam forum.
First I try to use that: https://github.com/codestation/python-phpbb3 
but it does not work with many forums. I think it is not so hard to fix it but I tried and failed. I'm not good in python. I make some progress but not enough to use it. 
So I start this project.

To compile it, on windows, you have to install visual studio and Qt (for visual studio). 
and compile it as any Qt project:
> qmake publishedOnForum.pro
> nmake
then you can run it. Qt creator can be useful to do so. Open the project and then run it.
It can't be run on server. it needs graphical interface.

On Linux, you have to install qt5 with all modules about qt5webengine*
You can open it into QtCreator too or
> qmake publishedOnForum.pro
> make

# To run it

## login into all your forum using the main session
./publishedOnForum -n  -u "http://forum0.com/"
./publishedOnForum -n  -u "http://forum1.com/"
./publishedOnForum -n  -u "http://forum2.com/"
./publishedOnForum -n  -u "http://forum3.com/"

You will have to log in into all forum. So the software saves your session/cookie etc… and then it won't be needed next time to log in. Check "Remember me" 


## Login into all forum with second profile [Optionnal]
this step is useful if you need to publish on the same forum with two profiles.
./publishedOnForum -n  -p -u "http://forum0.com/"
./publishedOnForum -n  -p -u "http://forum1.com/"
./publishedOnForum -n  -p -u "http://forum2.com/"
./publishedOnForum -n  -p -u "http://forum3.com/"

Login in all forums with the second profile.



## Publish message with main profile

./publishedOnForum  -u "http://forum0.com/path/to/reply/form/of/the/right/topic" -m "my message"
./publishedOnForum  -u "http://forum1.com/path/to/reply/form/of/the/right/topic" -m "my message"
./publishedOnForum  -u "http://forum2.com/path/to/reply/form/of/the/right/topic" -m "my message"
./publishedOnForum  -u "http://forum3.com/path/to/reply/form/of/the/right/topic" -m "my message"

"http://forum3.com/path/to/reply/form/of/the/right/topic" looks like :
https://forum3.org/posting.php?mode=reply&f=42&t=220

## Publish message with second profile


./publishedOnForum  -p -u "http://forum0.com/path/to/reply/form/of/the/right/topic" -m "my message"
./publishedOnForum  -p -u "http://forum1.com/path/to/reply/form/of/the/right/topic" -m "my message"
./publishedOnForum  -p -u "http://forum2.com/path/to/reply/form/of/the/right/topic" -m "my message"
./publishedOnForum  -p -u "http://forum3.com/path/to/reply/form/of/the/right/topic" -m "my message"

**Comment by Pierstoval** [comment]
Thanks, will give it a try soon with this doc! 👍
